@startuml

报文模板库 "1" *-- "*" 报文模板: 包含 >
报文模板 "1" *-- "1" 报文记录: 生成 >
报文  "1" *-- "*" 报文记录: 包含 >
报文记录  "1" *-- "*" 报文字段: 包含 >
报文字段 "*" -- "*" 校验公式: 关联 >
报文字段 "1" *-- "*" 校验结果: 包含 >
校验结果 "1" -- "1" 校验公式: 对应 >
报文模板  "1" *-- "*" 报文字段: 包含 >
报文模板  "1" *-- "1" 报文: 对应 >


业务条线 "1" -- "*" 报文模板: 处理 >
业务条线 "1" -- "1" 业务制度: 定义 >
报文 "1" -- "1" 报送流程: < 报送
报送流程 "1" -- 业务制度: 参考 >
报送流程 -- 校验服务: 使用 >
报送流程 -- 补录服务: 使用 >
报送流程 -- 审核服务: 使用 >
报送流程 -- 上报服务: 使用 >

流程引擎 "1" -- "*" 报送流程: 管理 >
流程引擎 "1" -- "*" 业务制度: 参考 >


机构 <|- 行内机构
机构 <|- 统计机构
统计机构 "*" -- "*" 行内机构: < 归属
部门 "1" -- "*" 用户: < 属于
行内机构 "1" -- "*" 部门: < 下属于
部门 "*" -- "1" 部门: 下属于 >
行内机构 "1" -- "*" 行内机构: 隶属于 >

主体 <|- 用户
主体 <|- 机构
主体 <|- 部门

客体 "*" -- "1" 主体: 来自 >

主体 "*" -- "*" 角色: 具有 >
角色 "*" -- "*"  权限: 拥有 >
权限 "*" *-- "*" 客体: 包含 >
权限 "*" *-- "*" 操作: 包含 >
角色 "*" -- "*"  参数: 包含 >

操作 "1" -- "*" UI元素: 对应 >


报文 -|> 客体
报文记录 -|> 客体
报文字段 -|> 客体
报文模板库 -|> 客体
报文模板 -|> 客体

@enduml
